### ISSUE TITLE
HA fails to start with RC6

### ISSUE THREAD

**Issue by rdstodda** [gcobb321/icloud3_dev#2]
My HA config (windows) appears to go into a funny state and fails to start with RC6. I found that changing the icloud3 manifest.json to the following fixed it (it keeps a blank requirements line).

{
  "domain": "icloud3",
  "name": "iCloud3 Device Tracker",
  "documentation": "https://github.com/gcobb321/icloud3",
  "dependencies": [],
  "codeowners": ["@gcobb321"],
  "requirements": []
}

**Comment by gcobb321** [comment]
Thanks. I deleted the requirements line by mistake and posted it. All fixed now.
