### ISSUE TITLE
HA 101.x can't find entity Registry with RC

### ISSUE THREAD

**Issue by rdstodda** [gcobb321/icloud3_dev#3]
This is a strange one as it does not appear to have been changed recently in ICLOUD3. I haven't gone back in HA versions (100.x) to verify that it is HA causing it.

On startup I get the error:
[custom_components.icloud3.device_tracker] [Errno 2] No such file or directory: '/config/.storage/core.entity_registry'

Changing to give the full path (line 75 in device_tracker.py) fixes it.
HA_ENTITY_REGISTRY_FILE_NAME = "C:\\Users\\Dave\\AppData\\Roaming\\.homeassistant\\.storage\\core.entity_registry"

**Comment by gcobb321** [comment]
The default file name is based in running Home Assistant on a Pi in a hassio environment. However, the config parameter ‘entity _registry _file _name’ lets you override it if your environment is different. See document [here](https://gcobb321.github.io/icloud3_dev/#/chapters/2-config-parms?id=user-and-account-items)
