### ISSUE TITLE
Cannot create icloud account without 2FA

### ISSUE THREAD

**Issue by JeroenTuinstra** [gcobb321/icloud3_dev#7]
I am trying to follow setting up iCloud3 - it is not easy as all your references are to older versions of HA and many settings have changed position or are in other menu's. 
I am stuck with the instruction that one should create an icloud account without 2FA, yet that is no longer possible it seems. There is never the option to no have the 2fa. It asks for a telephone number with the setup and then 2fa is automatically turned on. 
In icloud there is no settings to turn it off.

So i guess icloud3 intergration has the same issues as core cloud integration - 2fa notifications all the time?

Is there anywhere (up-to-date) instructions to create an icloud account without 2fa? Or can icloud3 work with 2FA? It seems to boast this, but you cannot enter the 2fa code anywhere.

**Comment by JeroenTuinstra** [comment]
Thanks. I think I got it working. Just the notification didn't popup. Now I am stuck with a request for the 2fA code, yet I don't have the code anymore. 
Also I am not able to get Event Log added to my lovelace. I have followed the steps (again, the documentation is getting old and things are hard to find in the new version of HA).

So the icloud-event-log-card.js is automatically added to config/www/custom_cards
I managed to add the resource as: Settings > Dashboards > three dots > resources. Unfortuntately no feedback whether it is working.
But when I want to add the card to my dashboard it gives the error: 

```
Custom element doesn't exist: icloud-event-log-card

type: custom:icloud-event-log-card
icon: mdi:information-outline
path: icloud3-event-log
title: iCloud3 Event Log
```
Documentation is very sketchy on this.

**Comment by gcobb321** [comment]
It’s `icloud3-event-log-card`. You have `icloud-…`. 

That version is several years old and docs have not been updated. A new version, a full Integration, should be released sometime next month that brings everything up to date.

**Comment by JeroenTuinstra** [comment]
I retyped the error message. As I was not able to copy it. It did have the correct information. However in in the documentation it says to enter this is in the dashboard > resources: 
```
/local/custom_cards/icloud3-event-log-card.js
```
I saw in some thread where someone was also not able to setup the card that they did this: 

```
/local/custom_cards/icloud3-event-log-card.js?v=1.000
```

This seemed to do the trick. However the card is now updating like crazy and both my apple watch and iphone are constantly online offline or something. It slows HA to a grinding hold. What is this? And is the above code correct?

**Comment by JeroenTuinstra** [comment]
Without ?v=1.000, even after restarting (did it several times) the card does not work.
Have just restarted it and it is still flashing.

**Comment by gcobb321** [comment]
Check to see if it is really in the custom_cards directory. 

Check the HA log file (home-assistant.log) to see if there are any error messages. Also, iCloud3 adds entries about its startup status to the log file. That might show what is going on.

**Comment by JeroenTuinstra** [comment]
Another error message in the logs with regards to the card: 

```
Logger: frontend.js.latest.202211080
Source: components/system_log/__init__.py:256
First occurred: 17:49:27 (1 occurrences)
Last logged: 17:49:27

https://ha.inhortum.org/frontend_latest/app.0706b45e.js:850:0 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "icloud3-event-log-card" has already been used with this registry
```

**Comment by JeroenTuinstra** [comment]
Ah and one more about the device trackers: 

```
Logger: homeassistant.components.device_tracker
Source: components/device_tracker/legacy.py:559
Integration: Device tracker (documentation, issues)
First occurred: 17:44:33 (3129 occurrences)
Last logged: 17:49:51

The see service is not supported for this entity device_tracker.jeroens_iphone
The see service is not supported for this entity device_tracker.jeroens_apple_watch
```

**Comment by gcobb321** [comment]
The `see` error message is probably causing the problem. It is described [here](https://gcobb321.github.io/icloud3/#/chapters/1.8-troubleshooting-problems?id=the-see-service-is-not-supported-for-this-entity-device_tracker). That section also has info about the Event Log during startup. 

It’s always confusing when you have the ‘s in a device name. I always remove them on my devices. The iCloud3 messages in the log file and in the Event Log during startup show how iCloud converts the device name.

**Comment by JeroenTuinstra** [comment]
I commented the apple watch entry and the flashing stopped. However still wondering how to be able to add my apple watch to devices. In the original iCloud integration the device name was: ```device_tracker.jeroens_apple_watch```
So what would be the name in iCloud3. 

The log file is difficult to read as it flashing like crazy.

Also I did change the name of the iOS App device_tracker entity name. I still have the original iCloud integration installed ... is that causing the issue. Didn't want to remove it yet, as some automations are depending on it and iCloud3 was not working yet.

**Comment by JeroenTuinstra** [comment]
It states the following in the startup log: 

```
Family Sharing List devices that can be tracked >
jeroens_apple_watch > Jeroen's Apple Watch, Watch
jeroens_iphone > Jeroen's Iphone, Iphone
```
Yet adding jeroens_apple_watch to the devices, the log goes crazy again.

**Comment by gcobb321** [comment]
We’ll fix the watch issue later. What is the iOS app device name for the iPhone. It’s it `jeroens_iphone` or `jerones_iphone_[suffix]`?

**Comment by JeroenTuinstra** [comment]
For the app it is: ``` device_tracker.jeroens_iphone_app ```
I managed to get the apple watch working, this was my configuration in the config_ic3.yaml: 
```
devices:
  - device_name: jeroens_iphone
    name: Jeroen
    email: jeroentuinstra@gmail.com
    picture: jeroen.jpg
  - device_name: jeroens_apple_watch
    name: Jeroen
    picture: jeroen.jpg
```
I changed that to a different name for the apple watch: 

```
- device_name: jeroens_apple_watch
    name: "Jeroen's Watch"
    picture: jeroen.jpg
```
So the name is actually not the name of the person, but the name of the device?

**Comment by gcobb321** [comment]
The `name` can be anything. It’s just displayed on messages in the Event Log. The `device_name` is what controls everything.

**Comment by JeroenTuinstra** [comment]
I must say the card is also quite distorted both in Firefox and in Edge. 
![Schermafbeelding 2022-11-10 182457](https://user-images.githubusercontent.com/47460053/201164969-02ddabfd-746d-458d-899d-5354fcc12ff3.png)
![Schermafbeelding 2022-11-10 182714](https://user-images.githubusercontent.com/47460053/201164982-c3b0b04b-31e1-4f19-b4e1-61835ad1add6.png)

**Comment by JeroenTuinstra** [comment]
Sorry to put everything in one topic. I just heard so much good news about iCloud3, especially as a replacement for the iCloud integration in the core, which is having 2fa issues the whole time.
This integration is actually very complex to setup.

**Comment by gcobb321** [comment]
Now I see. Yeah, it would have to be different because of the Event Log. I’ll put a check in for that on v3. 

Version 3 is much easier to set up. No yaml, online configuration, device names and devices are selected on menu lists, etc. I’m still working on the docs and one other issue. The v3 docs are [here](https://gcobb321.github.io/icloud3_v3_docs/#/README) if you wanted to see what is coming up.

**Comment by JeroenTuinstra** [comment]
Ah okay ... looking forward to that release. 

Is it normal with every restart that it cannot find all devices? I get this error each time I restart HASS: 

```
This error originated from a custom integration.

Logger: custom_components.icloud3.device_tracker
Source: custom_components/icloud3/device_tracker.py:1003
Integration: icloud3 (documentation, issues)
First occurred: 19:04:11 (1 occurrences)
Last logged: 19:04:11

iCloud3 Setup Error > jeroens_apple_watch > The iOS App device_tracker entity was not found in the Entity Registry for this device.
```

**Comment by gcobb321** [comment]
The iOS app can not be installed on the watch. Add `iosapp_installed: False` to its configuration parameters. Then iCloud3 will not check the entity registry for it and you won’t get that error.

**Comment by JeroenTuinstra** [comment]
Thank you, that did the trick. Looking forward to version 3. 
I did open an issue about the lovelace card, as it is not rendered properly. Will try other cards later.

**Comment by gcobb321** [comment]
That it’s fixed in v3. It’s also because you are using an iPhone with limited real estate on the device name display line. It looks ok on a computer or an iPad.

**Comment by JeroenTuinstra** [comment]
It is actually from a computer screen. But the Lovelace is configured to in masonry. If I configure it for just 1 card it looks worse as everything is stretched over the whole place.  I did a partial screen grab. I will post some other ones with the full screen.

**Comment by JeroenTuinstra** [comment]
Here are the two screencaptures with the different modes: 

Masonry style dashboard: 

![Schermafbeelding 2022-11-11 151651](https://user-images.githubusercontent.com/47460053/201359170-11ad75c5-144b-40c8-9f94-ce60067b91a4.png)

Panel (1 card) style: 


![Schermafbeelding 2022-11-11 151734](https://user-images.githubusercontent.com/47460053/201359270-728720ff-9bae-4a2f-b4ea-0067571363f9.png)

**Comment by gcobb321** [comment]
The issue, I think, is the field size below the buttons containing the name/device_name on the left is too small to hold both values and extends past the start point of the ‘Refreshed: ….’ Or the alert notification field on the right. This causes html to start The right hand field on another line which then forced the log item headers to start in the middle of the screen, giving you the results you see.  V3 does not resist the friend name on the left and reduces the text on the right which fixes this.

**Comment by JeroenTuinstra** [comment]
Is there any idea when this version would be available?
